Salesforce-Investiment/force-app/main/default/objects/Crypto_asset__c/Crypto_asset__c.object-meta.xml
<CustomObject>
    <label>Crypto Asset</label>
    <nameField>
        <label>Crypto Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crypto Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce-Investiment/force-app/main/default/objects/Crypto_asset__c/fields/Cryptocurrency__c.field-meta.xml
<CustomField>
    <fullName>Cryptocurrency__c</fullName>
    <label>Cryptocurrency</label>
    <referenceTo>Cryptocurrency__c</referenceTo>
    <relationshipLabel>Crypto Assets</relationshipLabel>
    <relationshipName>Crypto_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Crypto_asset__c/fields/Cryptocurrency_price_in_BRL__c.field-meta.xml
<CustomField>
    <fullName>Cryptocurrency_price_in_BRL__c</fullName>
    <formula>Cryptocurrency__r.Price_in_BRL__c</formula>
    <label>Cryptocurrency price in BRL</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Crypto_asset__c/fields/Cryptocurrency_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cryptocurrency_Quantity__c</fullName>
    <label>Cryptocurrency Quantity</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Crypto_asset__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Cryptocurrency__c/Cryptocurrency__c.object-meta.xml
<CustomObject>
    <label>Cryptocurrency</label>
    <nameField>
        <label>Cryptocurrency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cryptocurrencys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce-Investiment/force-app/main/default/objects/Cryptocurrency__c/fields/Price_in_BRL__c.field-meta.xml
<CustomField>
    <fullName>Price_in_BRL__c</fullName>
    <label>Price in BRL</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Cryptocurrency__c/fields/Price_in_USDT__c.field-meta.xml
<CustomField>
    <fullName>Price_in_USDT__c</fullName>
    <label>Price in USDT</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/objects/Cryptocurrency__c/fields/Total_Cryptocurrency__c.field-meta.xml
<CustomField>
    <fullName>Total_Cryptocurrency__c</fullName>
    <label>Total Cryptocurrency</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Salesforce-Investiment/force-app/main/default/classes/UpdateCryptocurrencyCallout.cls
Global class UpdateCryptocurrencyCallout {

    @InvocableMethod(label='Update Cryptocurrency')
    public static void updateCriptocurrency(List<Request> listRequest){
        System.debug(listRequest);
        
        Set<Id> setIdCryptocurrency = new Set<Id>();
        for(Request req : listRequest){
            setIdCryptocurrency.add(req.recordId);
        }
        
        List<Cryptocurrency__c> listCryptocurrency = getCryptocurrencyFromSetId(setIdCryptocurrency);
        
        for(Cryptocurrency__c crypto : listCryptocurrency){
            if(crypto.Name == 'Bitcoin'){
                updateBitcoin(crypto);
            }
        }
        
        update listCryptocurrency;
    }
    
    
    public static void updateBitcoin(Cryptocurrency__c crypto){
		
        String binanceAPIUrl = 'https://api3.binance.com';

        HttpResponse btcUSDTResponse = CalloutRequester.getResponse(binanceAPIUrl + '/api/v3/ticker/price?symbol=BTCUSDT');
        HttpResponse btcBRLResponse = CalloutRequester.getResponse(binanceAPIUrl + '/api/v3/ticker/price?symbol=BTCBRL');

        if(btcUSDTResponse.getStatusCode() == 200) {
			BinanceResponse usdtParsedResponse = (BinanceResponse) JSON.deserialize(btcUSDTResponse.getBody(), UpdateCryptocurrencyCallout.BinanceResponse.class);
            BinanceResponse brlParsedResponse = (BinanceResponse) JSON.deserialize(btcBRLResponse.getBody(), UpdateCryptocurrencyCallout.BinanceResponse.class);

                if(crypto.Name == 'Bitcoin'){
                    List<Crypto_asset__c> bitcoinCryptoAssets = crypto.Crypto_Assets__r;
                    
                    System.debug(crypto);

                    crypto.Price_in_USDT__c = Double.valueOf(usdtParsedResponse.price);
                    crypto.Price_in_BRL__c = Double.valueOf(brlParsedResponse.price);

                    if(!bitcoinCryptoAssets.isEmpty()){
                    	crypto.Total_Cryptocurrency__c = 0;
                    	for(Crypto_Asset__c criptoAsset : bitcoinCryptoAssets){
                            if(criptoAsset.Operation__c == 'Sell') {
                                crypto.Total_Cryptocurrency__c -= criptoAsset.Cryptocurrency_Quantity__c;
                            } else if(criptoAsset.Operation__c == 'Buy') {
                                crypto.Total_Cryptocurrency__c += criptoAsset.Cryptocurrency_Quantity__c;
                            }
                    	}
                    }
                }
            //}
            
            //update criptoCurrency;
            
        }
        
        
    }
    
    private static List<Cryptocurrency__c> getCryptocurrencyFromSetId(Set<Id> setIdCryptocurrency){
        return [SELECT Id, Name, (SELECT Id, Operation__c, Cryptocurrency__c, Cryptocurrency_price_in_BRL__c, Cryptocurrency_Quantity__c FROM Crypto_Assets__r) FROM Cryptocurrency__c WHERE Id in: setIdCryptocurrency];
    }
    
    class BinanceResponse {
        public String symbol;
        public String price;
    }
    
    global class Request {
        @InvocableVariable
        global String recordId;
    }

}